spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xjl241012
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      host: 127.0.0.1
      port: 6379



mybatis:
  type-aliases-package: com.examination.entity
  mapper-locations: classpath:mapper/*.xml
#pagehelper:
#  dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
logging:
  level:
    root: info
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
