spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xjl241012
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
##  type-aliases-package: com.examination.entity
##  mapper-locations: classpath:mapper/*.xml